routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/login/login');
});

Route::group(['as' => 'index.', 'prefix' => 'index'], function(){
    Route::get('index', ['as' => 'index', 'uses' => 'IndexController@index']);
});

Route::group(['as' => 'login.', 'prefix' => 'login'], function(){
    Route::post('login', ['as' => 'login', 'uses' => 'LoginController@index']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'LoginController@create']);
});

Route::group(['as' => 'setor.', 'prefix' => 'setores'], function(){
    
    Route::get('index',['as' => 'index', 'uses' => 'SetorController@index']);
    Route::get('create',['as' => 'create', 'uses' => 'SetorController@create']);
    Route::post('save',['as' => 'store', 'uses' => 'SetorController@store']);
    Route::get('{id}/edit',['as' => 'edit', 'uses' => 'SetorController@edit']);
    Route::post('{id}/update',['as' => 'update', 'uses' => 'SetorController@update']);
    Route::get('{id}/remove',['as' => 'destroy', 'uses' => 'SetorController@destroy']);
    
});

Route::group(['as' => 'colaborador.', 'prefix' => 'colaboradores'], function(){
    
    Route::get('index',['as' => 'index', 'uses' => 'ColaboradorController@index']);
    Route::get('create',['as' => 'create', 'uses' => 'ColaboradorController@create']);
    Route::get('search',['as' => 'show', 'uses' => 'ColaboradorController@show']);
    Route::post('save',['as' => 'store', 'uses' => 'ColaboradorController@store']);
    Route::get('{id}/edit',['as' => 'edit', 'uses' => 'ColaboradorController@edit']);
    Route::post('{id}/update',['as' => 'update', 'uses' => 'ColaboradorController@update']);
    Route::get('{id}/remove',['as' => 'destroy', 'uses' => 'ColaboradorController@destroy']);
    
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Setor.php
<?php

namespace Fluidi;

use Illuminate\Database\Eloquent\Model;

class Setor extends Model
{
    protected $fillable = [
        'descricao',
    ];
}

app/Http/Controllers/SetorController.php
<?php

namespace Fluidi\Http\Controllers;

use Fluidi\Setor;
use Illuminate\Http\Request;
use Fluidi\Http\Requests;
use Fluidi\Http\Requests\SetorRequest;

class SetorController extends Controller
{   
    
    public function index()
    {
         return view('setor.edit');
    }
    
    public function create()
    {
        $setores = Setor::all();              
        return view('setor.create', compact('setores'));    
    }
    
    public function store(SetorRequest $request)
    {   
        $setor = new Setor();        
        $setor->descricao = $request->get('descricao');
        $setor->save();
        
        $request->session()->flash('flash_message',['msg'=>"Setor " . $setor->descricao . " adicionado com Sucesso!"]);
        
        return redirect()->route('setor.create'); 
               
    }
    
    public function show(Setor $setor)
    {
        
    }
    
    public function edit($id)
    {
        $setor = Setor::find($id);
        return view('setor.edit', compact('setor'));              
    }
    
    public function update(SetorRequest $request, $id)
    {
        $setor = Setor::find($id);
        $setor->descricao = $request->get('descricao');
        $setor->save();

        $verificaConteudoCampo = $request->get('verificaConteudoCampo');

        if($verificaConteudoCampo == ''){
             return redirect()->route('setor.create');
        }
        else
        {   
            $request->session()->flash('flash_message',['msg'=>"Setor " . $setor->descricao . " alterado com Sucesso!"]);    

            return redirect()->route('setor.create');
        }        
         
    }
    
    public function destroy(Setor $setor)
    {
        
    }
}

resources/views/setor/create.blade.php
@extends('welcome')

@section('titulo','Novo Setor')

@section('content')
<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/estilos_gerais.css') }}"/>
<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/setor.css') }}"/>

<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/datatables/media/css/dataTables.bootstrap.css') }}">
<script type="text/javascript" charset="utf8" src="{{ asset('/datatables/media/js/jquery.js') }}"></script>
<script type="text/javascript" charset="utf8" src="{{ asset('/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript" charset="utf8" src="{{ asset('/datatables/media/js/dataTables.bootstrap.js') }}"></script>
<script type="text/javascript" charset="utf8" src="{{ asset('/css/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" charset="utf8" src="{{ asset('/js/setor.js') }}"></script>

@if(session()->has('flash_message'))
<!-- Modal Mensagem de Sucesso -->
	<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
						<h4 class="modal-title">Atenção!</h4>
					</div>
					<div class="modal-body">
						<div id="msgSucesso">
		  		            <p id="msgVazia">{{ session()->get('flash_message')['msg'] }}</p> 
		  	            </div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" data-dismiss="modal"><span class="glyphicon glyphicon-ok"></span> Ok</button>
					</div>
				</div>

			</div>
	</div>	
@endif	
		<h3>Novo Setor</h3>		
		<hr>
		<form id="formSetor" role="form" method="post" action="{{ route('setor.store') }}">
	        {{ csrf_field() }}
			<div class="form-group {{ $errors->has('descricao') ? 'has-error' : '' }}">				
				<label for="txtDescricao">Descrição:</label> 
				<input type="text" class="form-control input-sm" id="txtDescricao" name="descricao" value="{{ old('descricao') }}">				
					<span class="help-block">{{ $errors->first('descricao') }}</span>				
			</div>	
			<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
		</form>
		<br>
	<!-- Tabela Refente ao Cadastro dos Dados do Setor Plugin usado para formatação da tabela: DataTable 1.10.7-->		
		<table id="tbl_setor"
			class="table table-striped table-bordered table-condensed table-hover">
			<thead>
				<tr>
					<th width="10%">Id</th>
					<th>Descrição</th>
					<th width="10%">Ações</th>
				</tr>
			</thead>
			<tbody>					
				@foreach ($setores as $setor)			
					<tr>
						<td id="tdId">{{ $setor->id }}</td>
						<td id="tdDescricao">{{ $setor->descricao }}</td>
						<td id="tdAcoes">
							<a href="/setores/{{$setor->id}}/edit" class="btn btn-primary btn-xs"
								data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Alterar Setor">
							<span class="glyphicon glyphicon-edit"></span></a>							
							<!--
							<a href="#" class="btn btn-danger btn-xs btnexcluir"
								data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Excluir Setor">
							<span class="glyphicon glyphicon-trash"></span></a>
							-->						
						</td>
					</tr>				
				@endforeach
			</tbody>
		</table>
@endsection    

resources/views/setor/edit.blade.php
@extends('welcome')

@section('titulo','Alterar Setor')

@section('content')
<head>	
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/estilos_gerais.css') }}">
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/alterar_setor.css') }}">
	<script type="text/javascript" charset="utf8" src="{{ asset('/js/alterar_setor.js') }}"></script>
	<title>Alterar Setor</title>
</head>
@if(session()->has('flash_message'))
<!-- Modal Mensagem de Sucesso -->
	<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
						<h4 class="modal-title">Atenção!</h4>
					</div>
					<div class="modal-body">
							<div id="msgSucesso">
		  		                 <p id="msgVazia">{{ session()->get('flash_message')['msg'] }}</p> 
		  	                </div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" data-dismiss="modal"><span class="glyphicon glyphicon-ok"></span> Ok</button>
					</div>
				</div>
			</div>
		</div>	
@endif				
		<h3>Alterar Setor</h3>
		<hr>
		<form id="formAlterar" role="form" method="post" action="/setores/{{$setor->id}}/update">
		 {{ csrf_field() }}
		 <input type="hidden" name="_method" value="post">
			<div class="form-group {{ $errors->has('descricao') ? 'has-error' : '' }}">
				<label for="txtDescricao">Descrição:</label> 
					<input type="text" class="form-control input-sm" id="txtDescricao" name="descricao" value="{{ $setor->descricao }}"> 
					<span class="help-block">{{ $errors->first('descricao') }}</span>
					<input type="hidden" class="form-control" id="txtId" name="id" value="{{ $setor->id }}">
					<input type="hidden" class="form-control" id="txtVerificaConteudo" name="verificaConteudoCampo">
			</div>
			<button id="btnSalvar" type="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
			<a href="{{ route('setor.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar</a>
		</form>
	<br>
@endsection

resources/views/setor/remove.blade.php
@extends('welcome')

@section('titulo','Excluir Setor')
	
@section('content')
<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/bootstrap/css/bootstrap.min.css') }}"/>
<script type="text/javascript" charset="utf8" src="{{ asset('/js/jquery-2.1.4.js') }}"></script>	
<script type="text/javascript" charset="utf8" src="{{ asset('/css/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript">

	$(document).ready(function() {
	
		$('#myModalExcluir').modal('show');
	
	});	

</script>


	     <!-- Modal Mensagem Remove -->
      <div id="myModalExcluir" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<!-- <button type="button" class="close" data-dismiss="modal" >&times;</button> -->
						<h4 class="modal-title">Atenção!</h4>
					</div>
					<div class="modal-body">
							<div id="msgSucesso">
		  		                 <p id="msgVaziaExcluir">Deseja realmente excluir o setor: ${setor.descricao}?</p> 
		  	                </div>
					</div>
					<div class="modal-footer">
							<input type="hidden" class="form-control input-sm" id="txtDescricao" name="setor.descricao" value="${setor.descricao}"> 
					        <input type="hidden" class="form-control" id="txtId" name="setor.id" value="${setor.id}">
					        <input type="hidden" class="form-control" id="txtVerificaConteudo">
															
			               	<a href="${linkTo[SetorController].remove(setor.id, setor.descricao)}" class="btn btn-danger"><span class="glyphicon glyphicon glyphicon-ok"></span> Excluir</a>
			                <a href="${linkTo[SetorController].formulario}" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar</a>
			        </div>
				</div>
			</div>
		</div>			