routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/login/login');
});

Route::group(['as' => 'index.', 'prefix' => 'index'], function(){
    Route::get('index', ['as' => 'index', 'uses' => 'IndexController@index']);
});

Route::group(['as' => 'login.', 'prefix' => 'login'], function(){
    Route::post('login', ['as' => 'login', 'uses' => 'LoginController@index']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'LoginController@create']);
});

Route::group(['as' => 'setor.', 'prefix' => 'setores'], function(){
    
    Route::get('index',['as' => 'index', 'uses' => 'SetorController@index']);
    Route::get('create',['as' => 'create', 'uses' => 'SetorController@create']);
    Route::post('save',['as' => 'store', 'uses' => 'SetorController@store']);
    Route::get('{id}/edit',['as' => 'edit', 'uses' => 'SetorController@edit']);
    Route::post('{id}/update',['as' => 'update', 'uses' => 'SetorController@update']);
    Route::get('{id}/remove',['as' => 'destroy', 'uses' => 'SetorController@destroy']);
    
});

Route::group(['as' => 'colaborador.', 'prefix' => 'colaboradores'], function(){
    
    Route::get('index',['as' => 'index', 'uses' => 'ColaboradorController@index']);
    Route::get('create',['as' => 'create', 'uses' => 'ColaboradorController@create']);
    Route::get('search',['as' => 'show', 'uses' => 'ColaboradorController@show']);
    Route::post('save',['as' => 'store', 'uses' => 'ColaboradorController@store']);
    Route::get('{id}/edit',['as' => 'edit', 'uses' => 'ColaboradorController@edit']);
    Route::post('{id}/update',['as' => 'update', 'uses' => 'ColaboradorController@update']);
    Route::get('{id}/remove',['as' => 'destroy', 'uses' => 'ColaboradorController@destroy']);
    
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Colaborador.php
<?php

namespace Fluidi;

use Illuminate\Database\Eloquent\Model;

class Colaborador extends Model
{
    protected $fillable = [

            'nome',
            'login',
            'senha',
            'confirmaSenha',
            'email',
            'tipoColaborador',
            'setor_id', 
    ];

    public function setor()
    {
        return $this->belongsTo('Fluidi\Setor');
    }
}

app/Http/Controllers/ColaboradorController.php
<?php

namespace Fluidi\Http\Controllers;

use Fluidi\Colaborador;
use Fluidi\Setor;
use Illuminate\Http\Request;
use Fluidi\Http\Requests;
use Fluidi\Http\Requests\ColaboradorRequest;

class ColaboradorController extends Controller
{
    public function index()
    {
        //
    }

    public function create()
    {
        $setores = Setor::all(); 
        return view('colaborador.create', compact('setores'));          
    }

    public function store(ColaboradorRequest $request)
    {
        $colaborador = new Colaborador();        
        $colaborador->nome = $request->get('nome');
        $colaborador->login = $request->get('login');
        $colaborador->senha = $request->get('senha');
        $colaborador->confirmaSenha = $request->get('confirmaSenha');
        $colaborador->email = $request->get('email');
        $colaborador->tipoColaborador = $request->get('tipoColaborador');
        $colaborador->setor_id = $request->get('setor_id');
        $colaborador->save();
        
        $request->session()->flash('flash_message',['msg'=>"Colaborador " . $colaborador->nome . " adicionado com Sucesso!"]);
        
        return redirect()->route('colaborador.create');
    }

    public function show()
    {
        $colaboradores = Colaborador::all();          
        return view('colaborador.show', compact('colaboradores'));        
    }

    public function edit($id)    {
        $setores = Setor::all();
        $colaborador = Colaborador::find($id);
        return view('colaborador.edit', compact('colaborador', 'setores'));  
    }

    public function update(ColaboradorRequest $request, $id)
    {
        $colaborador = Colaborador::find($id);             
        $colaborador->nome = $request->get('nome');
        $colaborador->login = $request->get('login');
        $colaborador->senha = $request->get('senha');
        $colaborador->confirmaSenha = $request->get('confirmaSenha');
        $colaborador->email = $request->get('email');
        $colaborador->tipoColaborador = $request->get('tipoColaborador');
        $colaborador->setor_id = $request->get('setor_id');
        $colaborador->save();

        $verificaConteudoCampo = $request->get('verificaConteudoCampo');

        if($verificaConteudoCampo == ''){
             return redirect()->route('colaborador.show');
        }
        else
        {   
            $request->session()->flash('flash_message',['msg'=>"Colaborador " . $colaborador->nome . " alterado com Sucesso!"]);    

            return redirect()->route('colaborador.show');

        }
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/colaborador/create.blade.php
@extends('welcome')

@section('titulo','Novo colaborador')

@section('content')
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/estilos_gerais.css') }}"/>	
	<script type="text/javascript" charset="utf8" src="{{ asset('/js/colaborador.js') }}"></script>
	
@if(session()->has('flash_message'))    
<!-- Modal Mensagem de Sucesso -->
	<div id="myModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
					<h4 class="modal-title">Atenção!</h4>
				</div>
				<div class="modal-body">
					<div id="msgSucesso">
						<p id="msgVazia">{{ session()->get('flash_message')['msg'] }}</p> 						
						<p id="opcoesModal">O que deseja fazer:</p>						
					</div>
				</div>
				<div class="modal-footer">					
					<a href="{{ route('colaborador.show') }}" class="btn btn-info">
						<span class="glyphicon glyphicon-search"></span> Consultar
					</a>
					<button type="button" class="btn btn-success" data-dismiss="modal">
						<span class="glyphicon glyphicon-plus"></span> Cadastrar
					</button>
					<a href="{{ route('index.index') }}" class="btn btn-primary">
						<span class="glyphicon glyphicon-remove"></span> Sair
					</a>					
				</div>
			</div>
		</div>		
	</div>
@endif	
		<h3>Novo Colaborador</h3>
		<hr>
		<br>			
		<form id="frmColaborador" role="form" method="post" action="{{ route('colaborador.store') }}">
         {{ csrf_field() }}							
				<div class="row">					
					<div class="col-md-3">
					    <div class="form-group {{ $errors->has('nome') ? 'has-error' : '' }}">												
							<label for="txtNome">Nome:</label> 
							<input type="text" class="form-control input-sm" id="txtNome" name="nome" value="{{ old('nome') }}">							
							 	<span class="help-block">{{ $errors->first('nome') }}</span>
						</div>
					</div>	
					<div class="col-md-3">
					    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">												
							<label for="txtEmail">Email:</label> 
							<input type="text" class="form-control input-sm" id="txtEmail" name="email" value="{{ old('email') }}">							
								<span class="help-block">{{ $errors->first('email') }}</span>							
						</div>
					</div>
					<div class="col-md-2">
					    <div class="form-group {{ $errors->has('login') ? 'has-error' : '' }}">												
							<label for="txtLogin">Login:</label> 
							<input type="text" class="form-control input-sm" id="txtLogin" name="login" value="{{ old('login') }}">						    
								<span class="help-block">{{ $errors->first('login') }}</span>											
						</div>
					</div>	
					<div class="col-md-2">
					    <div class="form-group {{ $errors->has('senha') ? 'has-error' : '' }}">												
							<label for="txtSenha">Senha:</label> 
							<input type="password" class="form-control input-sm" id="txtSenha" name="senha" value="{{ old('senha') }}">							
								<span class="help-block">{{ $errors->first('senha') }}</span>							
						</div>
					</div>
					<div class="col-md-2">
					    <div class="form-group {{ $errors->has('confirmaSenha') ? 'has-error' : '' }}">												
							<label for="txtConfirmaSenha">Confirme a senha:</label> 
							<input type="password" class="form-control input-sm" id="txtConfirmaSenha" name="confirmaSenha" value="{{ old('confirmaSenha') }}">							
								<span class="help-block">{{ $errors->first('confirmaSenha') }}</span>							
						</div>
					</div>		
				</div>
					<div class="row">					
						<div class="col-md-3">	
						    <div class="form-group {{ $errors->has('setor_id') ? 'has-error' : '' }}">													
								<label for="slcSetor">Setor:</label> 
								<select class="form-control input-sm" id="slcSetor" name="setor_id">
									<option></option>
									@foreach ($setores as $setor)									
										<option value="{{ $setor->id }}">{{ $setor->descricao }}</option>									
									@endforeach
								</select>								
									<span class="help-block">{{ $errors->first('setor_id') }}</span>								
							</div>
					    </div>					
					    <div class="col-md-3">
					        <div class="form-group {{ $errors->has('tipoColaborador') ? 'has-error' : '' }}">						
								<label for="slcTipo">Tipo:</label> 
								<select class="form-control input-sm" id="slcTipo" name="tipoColaborador">
										<option></option>
										<option value="Interno">Interno</option>
										<option value="Externo">Externo</option>
								</select>								
									<span class="help-block">{{ $errors->first('tipoColaborador') }}</span>								
							</div>
						</div>
					</div>													
			    		<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
		</form>		
@endsection  

resources/views/colaborador/edit.blade.php
@extends('welcome')

@section('titulo', 'Alterar Colaborador')

@section('content')
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/estilos_gerais.css') }}"/>
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/alterar_colaborador.css') }}"/>
	<script type="text/javascript" charset="utf8" src="{{ asset('/js/alterar_colaborador.js') }}"></script>
	<title>Alterar Colaborador</title>

@if(session()->has('flash_message'))  
<!-- Modal Mensagem de Sucesso -->
	<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
						<h4 class="modal-title">Atenção!</h4>
					</div>
					<div class="modal-body">
						<div id="msgSucesso">
		  		            <p id="msgVazia">{{ session()->get('flash_message')['msg'] }}</p> 
		  	            </div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" data-dismiss="modal"><span class="glyphicon glyphicon-ok"></span> Ok</button>
					</div>
				</div>
			</div>
		</div>
@endif        	
	<h3>Alterar Colaborador</h3>
		<hr>
		<br>
		<form id="frm_altera_colaborador" role="form" method="post" action="/colaboradores/{{$colaborador->id}}/update">						
			{{ csrf_field() }}
            <input type="hidden" name="_method" value="post">	
                <div class="row">				
					<div class="col-md-3">
						<div class="form-group {{ $errors->has('nome') ? 'has-error' : '' }}">					
							<label for="txtNome">Nome:</label> 
							<input type="text" 	class="form-control input-sm" id="txtNome" name="nome" value="{{ $colaborador->nome }}">
							<input type="hidden" class="form-control" id="txtId" name="id" value="{{ $colaborador->id }}">
							<input type="hidden" class="form-control" id="txtVerificaConteudo" name="verificaConteudoCampo">
							<span class="help-block">{{ $errors->first('nome') }}</span>
						</div>
					</div>	
					<div class="col-md-3">
						<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">					
							<label for="txtEmail">Email:</label> 
							<input type="text" class="form-control input-sm" id="txtEmail" name="email" value="{{ $colaborador->email }}">
							<span class="help-block">{{ $errors->first('email') }}</span>
						</div>
					</div>	
					<div class="col-md-2">
						<div class="form-group {{ $errors->has('login') ? 'has-error' : '' }}">					
							<label for="txtLogin">Login:</label> 
							<input type="text" 	class="form-control input-sm" id="txtLogin" name="login" value="{{ $colaborador->login }}" readonly="readonly">
							<span class="help-block">{{ $errors->first('login') }}</span>
						</div>
					</div>						
					<div class="col-md-2">
						<div class="form-group {{ $errors->has('senha') ? 'has-error' : '' }}">					
							<label for="txtSenha">Senha:</label> 
							<input type="password" 	class="form-control input-sm" id="txtSenha" name="senha" value="{{ $colaborador->senha }}" readonly="readonly">
							<span class="help-block">{{ $errors->first('senha') }}</span>
						</div>
					</div>	
					<div class="col-md-2">
						<div class="form-group {{ $errors->has('confirmaSenha') ? 'has-error' : '' }}">					
							<label for="txtConfirmaSenha">Confirmação Senha:</label> 
							<input type="password" 	class="form-control input-sm" id="txtConfirmaSenha" name="confirmaSenha" value="{{ $colaborador->confirmaSenha }}" readonly="readonly">
							<span class="help-block">{{ $errors->first('confirmaSenha') }}</span>
						</div>
					</div>
				</div>
					<div class="row">	
						<div class="col-md-3">
							<div class="form-group {{ $errors->has('setor_id') ? 'has-error' : '' }}">						
								<label for="slcSetor">Setor:</label> 
								<select class="form-control input-sm" id="slcSetor" name="setor_id">
									<option value="{{ $colaborador->setor->id }}">{{ $colaborador->setor->descricao }}</option>
									@foreach ($setores as $setor)									
										<option value="{{ $setor->id }}">{{ $setor->descricao }}</option>									
									@endforeach						
								</select>
								<span class="help-block">{{ $errors->first('setor_id') }}</span>
							</div>
						</div>						
						<div class="col-md-3">
							<div class="form-group {{ $errors->has('tipoColaborador') ? 'has-error' : '' }}">						
								<label for="slcTipo">Tipo:</label> 
								<select class="form-control input-sm" id="slcTipo" name="tipoColaborador">
									<option value="{{ $colaborador->tipoColaborador }}">{{ $colaborador->tipoColaborador }}</option>
									<option value="Interno">Interno</option>
									<option value="Externo">Externo</option>
								</select>
								<span class="help-block">{{ $errors->first('tipoColaborador') }}</span>
							</div>
						</div>															
			    </div>	
			<button id="btnSalvar" type="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
			<a href="{{ route('colaborador.show') }}" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-remove"></span> Cancelar</a>
		</form>	
	<br>
@endsection    

resources/views/colaborador/show.blade.php
@extends('welcome')

@section('titulo','Consulta Colaborador')

@section('content')
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/estilos_gerais.css') }}"/>
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/css/css/colaborador.css') }}"/>
	<link type="text/css" rel="stylesheet" media="screen" href="{{ asset('/datatables/media/css/dataTables.bootstrap.css') }}"/>
	<script type="text/javascript" charset="utf8" src="{{ asset('/datadables/media/js/jquery.js') }}"></script>
	<script type="text/javascript" charset="utf8" src="{{ asset('/datatables/media/js/jquery.dataTables.js') }}"></script>
	<script type="text/javascript" charset="utf8" src="{{ asset('/datatables/media/js/dataTables.bootstrap.js') }}"></script>
	<script type="text/javascript" charset="utf8" src="{{ asset('/js/consultar_colaborador.js') }}"></script>
	<title>Consultar Colaborador</title>
@if(session()->has('flash_message'))
<!-- Modal Mensagem de Sucesso -->
	<div id="myModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
					<h4 class="modal-title">Atenção!</h4>
				</div>
				<div class="modal-body">
					<div id="msgSucesso">
						<p id="msgVazia">{{ session()->get('flash_message')['msg'] }}</p> 
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">
						<span class="glyphicon glyphicon-ok"></span> Ok
					</button>
				</div>
			</div>
		</div>
	</div>	
@endif	
		<h3>Consultar Colaborador</h3>
		<hr>		
	<br>
	<!-- Tabela Refente ao Cadastro dos Dados do Colaborador Plugin usado para formatação da tabela: DataTable 1.10.7-->	
		<table id="tbl_colaborador" class="table table-striped table-bordered table-condensed table-hover">
			<thead>
				<tr>
					<th width="10%">Id</th>
					<th>Nome</th>
					<th>Email</th>
					<th>Tipo</th>
					<th>Setor</th>
 					<th width="10%">Ações</th>
				</tr>
			</thead>
			<tbody>
					@foreach ($colaboradores as $colaborador)									 			
					<tr>
						<td id="tdId">{{ $colaborador->id }}</td>
						<td id="tdNome">{{ $colaborador->nome }}</td>
						<td id="tdEmail">{{ $colaborador->email }}</td>
						<td id="tdTipo">{{ $colaborador->tipoColaborador }}</td>							
						<td id="tdSetor">{{ $colaborador->setor->descricao }}</td>						
						<td id="tdAcoes">
							<a href="/colaboradores/{{$colaborador->id}}/edit" class="btn btn-primary btn-xs"
								data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Alterar Colaborador">
							<span class="glyphicon glyphicon-edit"></span></a> 
							
							<!--
							<a href="${linkTo[ColaboradorController].excluir(colaborador.id, colaborador.nome)}" class="btn btn-danger btn-xs btnexcluir"
								data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Excluir Colaborador">
							<span class="glyphicon glyphicon-trash"></span></a>
							-->							
						</td>
					</tr>
				@endforeach				
			</tbody>
		</table>
@endsection 